### ISSUE TITLE
Switch state at boot?

### ISSUE THREAD

**Issue by Sustainable-Me** [Stutchbury/InputEvents#1]
How does one (especially a newb) get the state of a switch at boot?

**Comment by Stutchbury** [comment]
I'm going to make the dangerous assumption you mean in `setup()`. The `EventSwitch` state currently defaults to `HIGH` at boot and the state is not updated until the first `update()` in your `loop()` (there are/were reasons for this - see below).

So currently you have two options:

1. Read the state of the pin directly - you shouldn't need to do this via bounce if the switch is stable but not really the  `InputEvents` way of doing things, is it? :-)
2. Call `update()` once within your `setup()` and then read `isOn()` or `isOff()`. This has the risk of an event being fired but you could ignore that in your event handler.

In the Arduino world, you cannot get the state of globally declared objects *before* `setup()` because the framework doesn't startup things like `analogRead()` and `digitalRead()` early enough. This is why many libraries have a `begin()` function/method to be called in `setup()`.

I will investigate if `Bounce2` can check the state of a pin in the `EventSwitch` constructor and if not, consider having an optional `begin()` method.

Thank you very much for your question - it has got me thinking!

**Comment by Sustainable-Me** [comment]
Thanks for the quick response!  I did mean in setup..

I also came up with the read the pin directly and also concluded it didn't dovetail nicely with the InputEvents concept, LOL.  

Calling update() is convincing enough for me to start updating some code - thanks for the suggestion!.  The reason I am asking is I have a few projects with limit switches determining when something is open or closed.  If the power goes off, for example,  knowing the current state of the limit switch(s)  will tell me if something is open or closed (or even in-between).

**Comment by Stutchbury** [comment]
A bit of digging... so `Bounce2` doesn't appear to use the normal Arduino pin reads (not surprising as they are a little slow for checking debouncing) so this means I can set the 'startup' state of the switch in the `EventSwitch` constructor, even for an UNO.

I'll do a few more tests and likely do a release over the weekend.

WRT your limit switches, don't forget we are using `INPUT_PULLUP` for both switches and buttons. This means `LOW` is when the switch is closed (ie pulled to GND) and `HIGH` when open. This is why the events are named `ON` and `OFF` rather than `OPEN` and `CLOSED` and why we have the `reverseOnOff(bool rev=true)` method!

Not sure there will ever be a switch event fired called `IN-BETWEEN`... :-)

**Comment by Stutchbury** [comment]
I've updated `EventSwitch` to set the state in the constructor, so `isOn()` and `isOff()` will now accurately report the switch state in `setup()`. I've also updated the docs and the `Switch.ino` example.

Release v1.0.1 is now available in the PlatformIO registry and should be picked up by the Arduino registry soon.
